apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: docmanagement
  name: docmanagement
  namespace: codadev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: docmanagement
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: docmanagement
    spec:
      containers:
      - image: codaregistry.azurecr.io/documentmanagementservice:ENVIRONMENT-BUILD_NUMBER
        name: docmanagementapp
        imagePullPolicy: Always
        resources:
          requests:
            cpu: 10m
            memory: 512Mi
          limits:
            cpu: 100m
            memory: 1Gi
        ports:
          - containerPort: 8082
        env:
          - name: spring.profiles.active
            value: dev
          - name: env
            value: dev
status: {}

---

apiVersion: v1
kind: Service
metadata:
  name: docmanagement
  namespace: codadev
  labels:
    run: docmanagement
spec:
  ports:
  - port: 8082
    protocol: TCP
  selector:
    app: docmanagement
  type: ClusterIP
 
